import { sample } from 'lodash';
import { ItemTypes } from './constants';

const Words = {
  HUMAN_TITLE: () => sample([
    'Capt.',
    'Sgt.',
    'Dr.',
  ]),
  HUMAN_FIRST_NAME: () => sample([
    'Chance',
    'Hank',
    'Harry',
    'Joe',
    'Jon',
    'Philip',
    'Saul',
    'Pip',
    'Harrison',
    'Chip',
    'Max',
    'Chaz',
    'Chad',
    'Wil',
    'Jules',
    'Drake',
    'Reaves',
    'Link',
    'Klaus',
    'Ralph',
    'Edwin',
    'Eddie',
    'Chet',
    'Montgomery',
    'Bruce',
    'Cristof',
    'Major',
    'Jeremiah',
    'Red',
    'Fox',
    'Redd',
    'Ed',
    'Zip',
    'Jim',
    'Frank',
    'Tennesee',
    'Indiana',
    'Kentucky',
    'Alabama',
    'Mick',
    'Tex',
    'Rob',
    'Kid',
    'Kidd',
    'Flip',
    'Sid',
    'Tip',
    'Tim',
    'Tony',
    'Biff',
    'Cliff',
    'Mork',
    'Dallas',
    'Dwayne',
    'Pop',
    'Pip',
    'Kip',
    'Rip',
    'Rooster',
    'Rod',
    'Pierre',
    'Petr',
    'Mak',
    'Mac',
    'Grant',
    'Dusty',
    'Chaz',
    'Rick',
    'Chef',
    'Blake',
    'Finn',
  ]),
  HUMAN_LAST_NAME: () => sample([
    'Sharptooth',
    'Silvertongue',
    'McLeod',
    'Morningwood',
    'St. James',
    'Hellfire',
    'Ironguard',
    'Brawn',
    'Jennings',
    'Herringbone',
    'Lightswitch',
    'Thunderfoot',
    'Montague',
    'Johnson',
    'Hanson',
    'Deadweight',
    'Cornwell',
    'Cloverfield',
    'Wunderlust',
    'Samsonite',
    'Pilkington',
    'Cranberry',
    'Sanchez',
    'Wellington',
    'Hopper',
    'Chopper',
    'Billingsworth',
    'Cumberbatch',
    'Cornwallace',
    'Lipsyncington',
    'Yardstick',
    'Blastfurnace',
    'Hotfoot',
    'Marinara',
    'Lightfoot',
    'Stonefoot',
    'Ironside',
    'Stoneheart',
    'Ironheart',
    'Montana',
    'Rock',
    'Jones',
    'Smith',
    'Brown',
    'Ford',
    'Locke',
    'Stormwood',
    'Flameheart',
    'Van Buren',
    'Custer',
    'Cunningham',
    'Shortbread',
    'Townsend',
    'Cannon',
    'Glass',
    'Breakwind',
    'Harley',
    'Rhodes',
  ]),
  CHARACTER_NAME: () => sample([
    '{HUMAN_FIRST_NAME} {HUMAN_LAST_NAME}',
  ]),
  BIO_BEGINNING: () => sample([
    '{character} was born under a full moon',
    '{character} was born under a blood moon',
    '{character} was born under a harvest moon',
    '{character} was born into poverty',
    '{character} was born with a silver spoon in his mouth',
    '{character} was born under a highway overpass',
    '{character} was born in a hurricane',
    '{character} was born to a protitute and a coal miner',
  ]),
  BIO_TRAIT: () => sample([
    'cannot stand the sight of unpeeled grapes',
    'refuses to eat sitting down',
    'finds it difficult to share KitKat bars',
    'suffers from a chronic fear of chandeliers',
    'cannot shake the feeling that his body is riddled with worms',
    'shows off his six-pack abs to strangers routinely',
    'carries a hatchet with him everywhere, but refuses to use it',
  ]),
  BIO_CHEEV: () => sample([
    'A graduate of ITT Technical Institute',
    'This first in his class to steal a hot-air balloon',
    'An honors student since kindergarten',
    'This first man to swallow a cucumber whole',
    'A certified member of MENSA',
    'A leading hand model in his youth',
    'Once an esteemed ophthalmologist',
    'Once a beloved gym coach',
    'Once a competitive poker player',
  ]),
  BIO_STEP: () => sample([
    '{character} found that the romatic life of a sailor was the life for him',
    '{character} gave it all up for what he thought was love',
    '{character} turned to God and MDMA for spiritual fulfillment',
    '{character} gave it all up to become a pastry chef',
    '{character} found more happiness in the bottom of a chocolate milk bottle',
    '{character} left it all behind to work on his art',
    '{character} learned to play the bongos and pretty much forgot about everything else',
    '{character} dropped out of the limelight to work on growing dreadlocks',
  ]),
  BIO_TRAGIC: () => sample([
    'Unfortunately, an injury sustained from an unpopped popcorn kernel would shatter his dreams.',
    'Sadly, a broken heart left him hopeless and homeless.',
    'Unfortunately, an injury sustained from a competitive eating contest.',
    'But in the end, a snapped bungie jumping cable left him emotionally scarred.',
    'Unfortunately, an injury sustained from a rabid squirrel pack would put and end to his dreams.',
    'Sadly, he was double crossed by his best friend.',
    'But in the end, an all-too-accurate fortune cookie spelled out his own demise.',
    'Unfortunately, an injury sustained from falling down 337 flights of stairs would crush his dreams.',
  ]),
  BIO_END: () => sample([
    'Now he seeks glory and riches any way that he can...',
  ]),
  BIO: () => sample([
    '{BIO_BEGINNING}, and consequently {BIO_TRAIT}. {BIO_CHEEV}, {BIO_STEP}. {BIO_TRAGIC} {BIO_END}',
  ]),
  RAT_FIRST_NAME: () => sample([
    'Francis',
    'Felippe',
    'Cal',
    'Skeev',
    'Killet',
    'Kreen',
    'Sark',
  ]),
  RAT_TITLE: () => sample([
    'Cutter',
    'Skitterer',
    'Snapper',
    'Furry',
    'Whiskered',
    'Many-clawed',
    'Collector',
  ]),
  RAT_NAME: () => sample([
    '{RAT_TITLE} {RAT_FIRST_NAME}',
    '{RAT_FIRST_NAME} the {RAT_TITLE}',
  ]),
  CHIMP_FIRST_NAME: () => sample([
    'Chippers',
    'Cupcake',
    'Nanners',
    'Popeye',
    'Skippy',
    'Chatters',
    'Goodboye',
    'Fruitcake',
  ]),
  CHIMP_TITLE: () => sample([
    'Space Engineer',
    'Commander',
    'Orbital Captain',
    'Hose-Scrubber',
    'Captain',
    'Security Consultant',
    'Moon Architect',
    'Comrade',
  ]),
  CHIMP_NAME: () => sample([
    '{CHIMP_TITLE} {CHIMP_FIRST_NAME}',
    '{CHIMP_FIRST_NAME} the {CHIMP_TITLE}',
  ]),
};

const Monsters = {
  RAT: (o) => assign({
    name: Words.RAT_NAME(),
    race: 'rat man',
  }, o),
  CHIMP: (o) => assign({
    name: Words.CHIMP_NAME(),
    race: 'space chimp',
  }, o),
};

const Items = [{
  article: 'a',
  name: 'Truly Dope Hat',
  imageFile: 'hat-1.png',
  type: ItemTypes.HEAD,
  skill: 'dopeness',
  description: 'This hat is dope. It says so.',
},{
  article: 'an old pair of',
  name: 'Work Gloves',
  imageFile: 'gloves-1.png',
  type: ItemTypes.HANDS,
  skill: 'manliness',
  description: 'Yours are the softest hands to ever enter these gloves.',
},{
  article: 'a pair of',
  name: 'Wooly Winter Boots',
  imageFile: 'boots-1.png',
  type: ItemTypes.FEET,
  skill: 'warmth',
  description: 'The fuzzy bit feets nice on your ankles.',
},{
  article: 'a set of',
  name: 'Fancy Silk Gloves',
  imageFile: 'gloves-2.png',
  type: ItemTypes.HANDS,
  skill: 'class',
  description: 'CAUTION: Wearing these gloves may cause spontaneous outbreaks of posh English accents.',
},{
  article: 'a',
  name: 'Snazzy Outfit',
  imageFile: 'clothes-1.png',
  type: ItemTypes.CLOTHES,
  skill: 'bromancing',
  description: 'The jacket fits like a glove. Which would be great, if it was a glove.',
},{
//   article: 'a',
//   name: 'Satchel of Erens Seed',
//   imageFile: 'seed-bag-1.png',
//   type: ItemTypes.SPECIAL,
//   skill: 'urban farming',
//   description: 'A key ingredient in Hot Gorggonash Casserole. Highly valued among the forest peoples.',
// },{
  article: 'a pair of',
  name: 'Spiffy Loafers',
  imageFile: 'shoes-1.png',
  type: ItemTypes.FEET,
  skill: 'negotiating',
  description: 'Look at them shine.',
},{
  article: 'a',
  name: 'Dagger',
  imageFile: 'knife-3.png',
  type: ItemTypes.WEAPON,
  skill: 'stabbin',
},{
  article: 'a',
  name: 'Swiss Army Knife',
  imageFile: 'knife-2.png',
  type: ItemTypes.WEAPON,
  skill: 'neutrality',
},{
  article: 'a',
  name: 'Folding Knife',
  imageFile: 'knife-1.png',
  type: ItemTypes.WEAPON,
  skill: 'intimidation',
},{
  article: 'a',
  name: 'Revolver',
  imageFile: 'gun-1.png',
  type: ItemTypes.WEAPON,
  skill: 'country attitude',
},{
  article: 'a',
  name: 'Hatchet & Blade Set',
  imageFile: 'axe-1.png',
  type: ItemTypes.WEAPON,
  skill: 'woodcarving',
},{
  article: 'a pair of',
  name: 'Slittelo Heels',
  imageFile: 'shoes-2.png',
  type: ItemTypes.FEET,
  skill: 'curlytoes',
  description: 'Legends have told of these ancient torture devices. Now you cn wear them. Sexy!',
},{
  article: 'a set of',
  name: 'Shredded Threads',
  imageFile: 'clothes-2.png',
  type: ItemTypes.CLOTHES,
  skill: 'narcissism',
  description: 'Prior to The Event, precocious youth were known to dress as though the world had already ended.',
}];

module.exports = {
  Words,
  Monsters,
  Items,
};
